// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuv41kIULi4IvgjJtfo-sXDcr8DglFMW0',
    appId: '1:612189041155:web:a7ec8225548db6a4785436',
    messagingSenderId: '612189041155',
    projectId: 'calculator-app-fb8be',
    authDomain: 'calculator-app-fb8be.firebaseapp.com',
    storageBucket: 'calculator-app-fb8be.appspot.com',
    measurementId: 'G-XVPZGDFJWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBfoMZZtMRcIqsnz7C4Nh9sUdCGPdkfwQ',
    appId: '1:612189041155:android:333a6447c506c624785436',
    messagingSenderId: '612189041155',
    projectId: 'calculator-app-fb8be',
    storageBucket: 'calculator-app-fb8be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp_VjhzMxH-_8QQK90HZo8Qeoa52cLa5o',
    appId: '1:612189041155:ios:7e584aceea9de8f2785436',
    messagingSenderId: '612189041155',
    projectId: 'calculator-app-fb8be',
    storageBucket: 'calculator-app-fb8be.appspot.com',
    iosBundleId: 'com.example.calculatorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp_VjhzMxH-_8QQK90HZo8Qeoa52cLa5o',
    appId: '1:612189041155:ios:7e584aceea9de8f2785436',
    messagingSenderId: '612189041155',
    projectId: 'calculator-app-fb8be',
    storageBucket: 'calculator-app-fb8be.appspot.com',
    iosBundleId: 'com.example.calculatorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuv41kIULi4IvgjJtfo-sXDcr8DglFMW0',
    appId: '1:612189041155:web:8875abb42c4062dc785436',
    messagingSenderId: '612189041155',
    projectId: 'calculator-app-fb8be',
    authDomain: 'calculator-app-fb8be.firebaseapp.com',
    storageBucket: 'calculator-app-fb8be.appspot.com',
    measurementId: 'G-2KC4SWN26L',
  );
}
